### ISSUE TITLE
Having a reference value for protonation

### ISSUE THREAD

**Issue by xiki-tempula** [grimme-lab/crest#10]
It is nice that crest allows the user to protonate or deprotonate a molecular and give the energy for that. However, I think in most cases, it is more interesting to know whether the energy difference of adding a proton is larger or smaller than adding a proton to the water in gbsa water. I wonder if there is any reference value for a proton addition under gbsa water at gfn2 level?

**Comment by pprcht** [comment]
Since we've discussed this per mail, I'll close this issue
