### ISSUE TITLE
initial geometry optimization failed issue

### ISSUE THREAD

**Issue by xiaoshan198301** [grimme-lab/crest#105]
Hi,

I was trying to run CREST for conformer search for some organic molecules and got the error message as follows:

```
 -------------------------
 xTB Geometry Optimization
 -------------------------

  Initial geometry optimization failed!
  Please check your input.
ERROR STOP 
```

As the error message suggests, I thought it happened because the xTB geometry optimization could not converge. However, I used xTB itself and ran --opt with vtight option, the calculation converges normally. I also checked the xtb.out file generated by CREST, it also stated that the geometry optimization converged. Just wondering if you could help me with the issue. Some details of my calculation are found in the following

- Please find the input file I used and the xtb.out file are attached. 
- I used the following command `crest 1hk3.xyz --mquick -T 6` for the test. 
- Please note that I have tested any combination of the options for accuracy or number of threads, they all resulted in the same error message. 
- My xTB version is 6.4.1 and CREST version is 2.11.2. I have also tried xTB 6.4.0, the same happened.

Thanks,

Xiao
[1hk3.xyz.txt](https://github.com/grimme-lab/crest/files/8123242/1hk3.xyz.txt)
[xtb.out.txt](https://github.com/grimme-lab/crest/files/8123243/xtb.out.txt)

**Comment by xiaoshan198301** [comment]
Dear developers,

I think I have somehow found out the reason of the problem, but I am not sure whether that is the case or not. 

1. The calculation I described were performed on Apple M1 Pro chip. It seems to me that CREST would simply not run properly. The geometry optimization ERROR would always occur (even with the example files given in CREST GitHub). However, I did manage to get it working with some other molecules two days ago (they no longer work any more).
2. For this particular molecule, the topology changes after initial optimization. This is why the calculation why the calculation stops. But the `WARNING! Change in topology detected!` message were not generated. I still do not see why `Initial geometry optimization failed!` occurred.
3. All in all, to solve this particular problem, or run calculation for this particular system, I could run it on a computer with different CPU chip with `--noreftopo` turned on. However, I think it might still worth looking into why it had failed on Apple M1 Pro chip. (Please note that I have also tried to reinstall both CREST and xTB, or install xTB version 6.4.0, none of which solved the problem).

Thanks,

Xiao

**Comment by awvwgk** [comment]
If you are using MacOS 13 this might be related to a known OS-specific issue with GCC: https://fortran-lang.discourse.group/t/program-compiled-with-gfortran-does-not-write-to-output-file-on-macos-monterey/2297.

**Comment by xiaoshan198301** [comment]
Hi,

Thanks for the swift response. Yes, that is the issue, and I can confirm that `export GFORTRAN_UNBUFFERED_ALL=1` can fix the problem. Interestingly, the calculation would also be fine if, say, a new Conda environment were created. But I guess the problem would still occur if an error is found during the calculation, which was probably the trigger of my earlier failure.

Thanks again for the help. I will close the issue (and hoping that Apple can fix this problem with an update soon).

Xiao
