### ISSUE TITLE
QCG failed with the bacillaene example

### ISSUE THREAD

**Issue by pierre-girard-at-uga** [grimme-lab/crest#127]
Dear CREST developers

I was asked by chemists from my lab to install CREST in order to run QCG calculations.

I downloaded the required binaries :

- XTB 6.4.0 and 6.4.1
- CREST 2.11 and 2.11.2
- XTBIFF 1.1

On a cluster with the Linux kernel :

   ```
 $ uname -a
    Linux f-dahu 4.9.0-17-amd64 #1 SMP Debian 4.9.290-1 (2021-12-12) x86_64 GNU/Linux

```
I tried to play your 2 examples provided at https://xtb-docs.readthedocs.io/en/latest/crestqcg.html#example-applications (Thanks a lot for this very good documentation)

The second example (benzoic_acid) worked well, but the first one (bacillaene) failed for each combination of binary versions I tried.

The problem always arises during "quantum cluster growth: GROW" at the same iteration step :

```
       88  -575.443143  -13.60   -1145.73       1.183    -30.584     14.3  21.4   20510.8   normal
     Cluster energy not found
       Interaction Energy positiv, increasing outer wall pot by 5 %
     New scaling factor 0.97
     Cluster energy not found
       Interaction Energy positiv, increasing outer wall pot by 5 %
     New scaling factor 1.00
     Cluster energy not found
     Total Energy of cluster not found.
       89     0.000000 *******   ********       1.184      0.000     14.3  15.9   20665.8   normal
     Total Energy of cluster LMO computation not found
```

With the error :

```
    forrtl: severe (24): end-of-file during read, unit -6144, file /bettik/PROJECTS/pr-cecipex/girpierr/CREST/bacillaene.21142982/qcg_tmp/tmp_grow/xtbscreen.xyz
    Image              PC                Routine            Line        Source
    crest              00000000014CE6A8  Unknown               Unknown  Unknown
    crest              00000000015002C2  Unknown               Unknown  Unknown
    crest              000000000065F55D  Unknown               Unknown  Unknown
    crest              0000000000640414  Unknown               Unknown  Unknown
    crest              00000000006392D7  Unknown               Unknown  Unknown
    crest              000000000068DC98  Unknown               Unknown  Unknown
    crest              0000000000402242  Unknown               Unknown  Unknown
    crest              00000000016F7DD0  Unknown               Unknown  Unknown
    crest              000000000040210E  Unknown               Unknown  Unknown

```
Thank you for any help you can provide me to fix this problem.

Best regards

Pierre

**Comment by cplett** [comment]
Hi,
this seems to be a problem with the size of the wall potential. I checked the example, and it worked out. I guess that this error might sometimes occur by chance because the addition of the solvent molecules is at a certain cluster size a bit random. If a solvent molecule is added too close to the wall potential, the error you observe will occur. If you are planning to add many water molecules, it might be a good idea to directly increase the size of the wall potential by increasing the scaling factor to 1.0 ("--wscal 1.0" flag) or even larger values.

**Comment by yanfeiguan** [comment]
Hi, I am also facing the problem of running the bacillaene example. Which version of CREST and XTB worked out for you? And how did you set up the environment variable of (OMP_NUM_THREADS and OMP_STACKSIZE)? Thank you!

**Comment by pierre-girard-at-uga** [comment]
Hi Yanfeiguan,
I solved the problem by adding the option `--wscal 1.0`. I didn't set OMP_STACKSIZE, and I set OMP_NUM_THREADS with `export OMP_NUM_THREADS=${ncores},1`, and ncores is equal to 32, the number of cores of the computing server. Hope that helps. Pierre
