### ISSUE TITLE
reproducing published xtb --reactor ferrrocene decomposition example

### ISSUE THREAD

**Issue by sibo** [grimme-lab/crest#13]
I would like to reproduce the examples of ferrocene decomposition in https://pubs.acs.org/doi/10.1021/acs.jctc.9b00143 which used xtb's nanoreactor option. For the ferrocene example, tau_MTD was specified as 2ps. xtb's documentation say that the --reactor option is depreciated, and to use crest --nci. 

crest start.xyz -nci -ewin 120 -temp 6000 -len 100 -tstep 2000 -shake 0 --verbose
This gives unreasonably fast output that then crashes in seconds with "forrtl: severe(24) [...]" 

If I set -tstep to 200 or 20 fs, the initial MTDs do not finish, and CREST prompts me to manually try other values. If I set -tstep to 2fs, the crest algorithm is proceeding, but there is no conformers with extreme bond rearrangement like in the paper.

Can someone explain how to reproduce the ferrocene nanoreactor?

**Comment by pprcht** [comment]
Hello,
The information from the documentation seems to be incorrect. We are planning to do an automated version of the nano-reactor in `crest`, but the `--nci` mode is something else. The only thing the reactor and this mode have in common is a spherical potential, but it neither has a radius small enough to induce chemical reactions, nor has it the correct potential form (the nano-reactor requires a [logfermi](https://xtb-docs.readthedocs.io/en/latest/xcontrol.html?highlight=logfermi#different-potential-shapes) potential, while it is polynominal for the `crest` mode).

Currently there isn't an automated procedure for the reactor, but we have some workarounds that can already be used with the [`crest 2.11` development version](https://github.com/grimme-lab/crest/releases/tag/2.11-dev). There are 3 steps/commands to it:

1. Generate nano-reactor settings with the command `crest start.xyz --reactor --genpot <density> --genmtd <sim.length>` which will produce a file called `rcontrol` containing the correct `xtb` constraints. `<density>` can be the required nano-reactor density in g/cm³ like in the JCTC paper, `<sim.length>` is the metadynamics length in ps. All other settings, e.g. _k_ and _α_  for the metadynamics, must be directly edited in the `rcontrol` file. This requires some trial and error and is the reason why we haven't automatized it yet.
2. Run the metadynamics with the generated settings using `xtb` simply with the command `xtb start.xyz --gfn 2 --md --input rcontrol`. What you are interested in is then the trajectory saved as `xtb.trj`.
3. To so some (simple) fragment analyzation of `xtb.trj` use `crest coord --reactor --fragopt`. This will extract all fragments from the trajectory based on neighbor lists, optimize their geometry with `xtb` and sort them.

I hope this helps.

**Comment by sibo** [comment]
Thanks that is very helpful! I'm closing this issue.
