### ISSUE TITLE
Additional adduct forms for crest

### ISSUE THREAD

**Issue by tobigithub** [grimme-lab/crest#2]
**Is your feature request related to a problem? Please describe.**
The current crest version (Version 2.8.1, Fri  20. Dec 13:44:46 CET 2019 ) only allows for protonized [M+H]+ and deprotonized adduct forms [M-H]-. While these are the most important adducts electrospray mass spectrometry (ESI-MS) they are only two out of 300 different possible ions that are routinely observed. In the past many of these other adducts were simply ignored or found less important. With the advent of accurate mass spectrometry, many experiments and software solutions now report all additional species.

**Describe the solution you'd like**
A crest version that allows for additional adduct ions selected in the command line or in the parameter file, or input file.

**Describe alternatives you've considered**
None.

**If possible state how you can assist in providing data or code to to implement the feature**
Can provide list of most common adducts, for ESI-MS based on thousands of spectra.

**Additional context**
Maybe starting with the most common ones in the list, that do not require additional complex coding would be good. Basically replacing {H} with {Na} or similar. That means, complicated species with multiple ions or water losses, could be ignored in the beginning, but those with [M+Na]+, [M+Li]+ or  [M.Cl]- or [M+NH4]+ could be easily added.  The list contains 300 adducts, I only added the top 30.

````
| #  | Adduct name  | Count | Percent  |   |
|----|--------------|-------|----------|---|
| 1  | [M+H]+       | 98521 | 62.55381 |   |
| 2  | [M+2H]2+     | 18025 | 11.44459 |   |
| 3  | [M+H-H2O]+   | 13822 | 8.77598  |   |
| 4  | [M-H]-       | 9847  | 6.25214  |   |
| 5  | [M+Na]+      | 8679  | 5.51055  |   |
| 6  | [M+H-NH3]+   | 1882  | 1.19494  |   |
| 7  | [M+NH4]+     | 1161  | 0.73715  |   |
| 8  | [M-H-H2O]-   | 545   | 0.34604  |   |
| 9  | [M-H+2Na]+   | 519   | 0.32953  |   |
| 10 | [M-H+H2O]-   | 386   | 0.24508  |   |
| 11 | [M+NH4-H2O]+ | 362   | 0.22984  |   |
| 12 | [M+H+H2O]+   | 306   | 0.19429  |   |
| 13 | [M+H+Na]2+   | 288   | 0.18286  |   |
| 14 | [M+H+K]2+    | 276   | 0.17524  |   |
| 15 | [M-2H]2-     | 220   | 0.13968  |   |
| 16 | [M+2Na]2+    | 217   | 0.13778  |   |
| 17 | [M+2H-NH3]2+ | 216   | 0.13714  |   |
| 18 | [M+K]+       | 215   | 0.13651  |   |
| 19 | [M+H-2H2O]+  | 186   | 0.11810  |   |
| 20 | [M+3H]3+     | 105   | 0.06667  |   |
| 21 | [M+2H-H2O]2+ | 102   | 0.06476  |   |
| 22 | [M]+.        | 93    | 0.05905  |   |
| 23 | [M+2Na-H]+   | 81    | 0.05143  |   |
| 24 | [M-H+2K]+    | 80    | 0.05079  |   |
| 25 | [M+H-CO]+    | 73    | 0.04635  |   |
| 26 | [M+H-CO2]+   | 68    | 0.04318  |   |
| 27 | [M+H-CH2O2]+ | 60    | 0.03810  |   |
| 28 | [M-H-NH3]-   | 59    | 0.03746  |   |
| 29 | [M.Cl]-      | 56    | 0.03556  |   |
| 30 | [M+Li]+      | 49    | 0.03111  |   |
````

**Comment by lizhiq16** [comment]
@awvwgk @pprcht  what's the function of automatic bond length constraint (-cbonds) in crest-2.10?

**Comment by awvwgk** [comment]
@lizhiq16 Please don't post off-topic in other threads and open a new issue for this question.
