### ISSUE TITLE
Problem with strucutures rejected due to topology mismatches

### ISSUE THREAD

**Issue by PellizzeriLab** [grimme-lab/crest#26]
I am attempting to sort a trajectory for a metal cluster using cregen. Previously this caused no issues until I had to redownload the 2.11_dev version of crest (Version 2.11dev, Fri 15. Jan 12:42:14 CEST 2021). Now out of my 5000 configurations all but the reference structure is being rejected due to topology mismatches. Using 2.10.2 I get the expected result (67 unique clusters) a similar result to what I got with a previous version of crest 2.11_dev (Version 2.11dev, Mon 21. Sep 10:32:08 CEST 2020).

The reference structure and trajectory that I am using are attached.

[xtb.txt](https://github.com/grimme-lab/crest/files/5851069/xtb.txt)
[struc.txt](https://github.com/grimme-lab/crest/files/5851071/struc.txt)

I am running the command as: 
crest struc.txt -cregen xtb.txt -ewin 100

**Comment by pprcht** [comment]
Oh, yes, metal clusters don't seem to work with the topology. This kind of makes sense, there will be a lot of bond reformations.
You can turn the topology checks off with `--notopo`. This yields 70 structures for your example if I test it on my machine.

**Comment by PellizzeriLab** [comment]
Perfect, thank you for helping me out with this.
