### ISSUE TITLE
Crest use

### ISSUE THREAD

**Issue by Vale1987** [grimme-lab/crest#27]
Dear sirs,

I am trying to use Crest for my research in supramolecular cages and I cannot get it to work. The crest output file does not look as the one in the example. I tried many times to change the command line as I am not sure if it is correct. Unfortunately, the calculation stops after 7 seconds and the output file does not show any errors.
I would be very happy for any help on this.

Thanks in advance

Kind regards
Valentinos

**Comment by awvwgk** [comment]
Without some input and output it is unlikely that we can help you with your setup. Please provide a more complete description / output of the error you are encountering,

**Comment by Vale1987** [comment]
Dear Sebastian,


Thanks for your respond. Fortunately I was able to solve the issue by myself. It was just my missrunderstanding of the guidelines.


However, I do have an additional question concerning STDA-xTB. I am working on supramolecular cages and I tried to calculate the uv-vis and cd spectra of

a chiral cage. The result I got of the calculated spectra was showing some extra peaks and the shifts were also slightly off.


In one of you publications you do an MD calculation before the STDA calculation. As far as I understood you use the average of

all the calculated states of the MD trajectory and use this as an input for the STDA-xTB.


My question is: do you have any information on how to do that? Do you manually calculate the average of all the generated coordinates and use that?

Or there is a different way to do that so I can improve the accuracy?


Thanks in advance,


Kind regards

Valentinos Mouarrawis, MSc.
Ph.D. candidate
Universiteit van Amsterdam
Faculty of Science
van 't Hoff Institute for Molecular Sciences
Department of Homogeneous, Supramolecular and Bio-Inspired Catalysis (HomKat) group
Postbus 94720
1090 GS Amsterdam
________________________________

**Comment by awvwgk** [comment]
Please open an issue at the [sTDA repository](https://github.com/grimme-lab/stda/issues/new/choose) to get the right developers to help you with your questions.

I'll close this issue as resolved for crest here.
