### ISSUE TITLE
unique conformers relative energies print on the screen

### ISSUE THREAD

**Issue by lizhiq16** [grimme-lab/crest#3]
In the previous version of crest-2.9, the relative energy of each “unique conformers” will be output on the screen at the end of calculation. Now, this output is cancelled, and instead a "crest.energies" file is output. This function is what I really want, but I still want this energy to be displayed on the screen directly sometimes. I hope you can make adjustments.

Two days ago I asked some unrelated questions under another post, I apologize for that. But I still want to ask:
 what's the function of automatic bond length constraint (-cbonds) in crest-2.10?

Best wishes!

**Comment by fabothch** [comment]
To answer the second part: the -cbonds option allows the user to constrain all bond lengths automatically by providing a force constant.  This option has been implemented for being used together with the GFN-FF  force field e.g. for metal organic complexes. This is used to avoid dissociation if the forces in the metadynamics simulation are very strong. This option is just for convenience, the user can supply any constraint manually if desired.

The first part has to be answered by @pprcht .

**Comment by pprcht** [comment]
I surely can add some kind of `verbose` flag for that, but since this printout is (was) right at the end of the program anyways, it would probably be simpler to use  `cat crest.energies` in the command line, just after execution of the program.

**Comment by awvwgk** [comment]
I have to admit, that I also liked this particular printout in the standard output, made it easy to quickly get a rough idea of the ensemble.

**Comment by lizhiq16** [comment]
I often calculate a batch of molecules. Generally, I directly save the screen output separately as a file for further check, so I don’t want to save another more file (because there will be too many files). It's OK to keep current output, and frankly speaking, I prefer the current form output when dealing with a single task. I will add "crest.energies"  to the end of the file I saved.
Thank you very much for your kindly reply.
