### ISSUE TITLE
Fixing and confining in CREST

### ISSUE THREAD

**Issue by KeweiZhao** [grimme-lab/crest#32]
Hi all,

Is it possible to use fixing or confining in CREST? If I put $fix or $wall in .xcontrol, the program (v2.11 with xtb-6.4.0, NCI job) won't run MTD Iteration 2 and stop. Please find the log file of CREST and SLURM attached.

[crest.log](https://github.com/grimme-lab/crest/files/5926072/crest.log)
[slurm-874099.log](https://github.com/grimme-lab/crest/files/5926075/slurm-874099.log)

Thanks,
Kewei

**Comment by pprcht** [comment]
It should work, we are using it in several projects. From your output I can see that the program reads the constraint correctly, but the calculations crash in the MTD simulations of the second iteration. The message `Warning: file METADYN1/xtb.trj is empty!` indicates that the problem arises in the simulations at xtb level. CREST should make a copy of the failed calculations including all in- and outputs in a directory called `FAILEDMTD`, maybe have a look in there (mainly the `xtb.out` file) to see what breaks.

**Comment by KeweiZhao** [comment]
Yes. I think the MTD crashed because of the constrain applied (polynomial might be too steep). And I didn't find the "FAILEDMTD" directory. The problem was solved after switching to logfermi. Thanks again!
