### ISSUE TITLE
Large molecules

### ISSUE THREAD

**Issue by bfmilne** [grimme-lab/crest#34]
Hi,

I am working with some systems with ~250 atoms and as long as I use GFNFF for the geometry minimisation/MD I am OK. I want to compare with GFN2 but the initial geometry optimisation fails. It works fine when I use XTB alone, so it seems likely to be an atom number limit problem in CREST. I tried recompiling after changing all instances of 'maxat' from 200 to 2000 but it still fails. Any help would be greatly appreciated.

XTB=6.4.0
CREST=2.11

Cheers,
Bruce

**Comment by pprcht** [comment]
`maxat` is only relevant for the symmetry detection and has nothing to do with any system size limitation for calculations. From the technical side there is no atom number limit in CREST, we did proteins with it.

What exactly does your output say, where does it fail? Maybe at GFN2 level there is a change in topology. GFN-FF will always keep bonds, but GFN2 might change them upon optimization. XTB does not check for this change and hence will not complain, CREST however will do that because this is important for future sorting.

**Comment by bfmilne** [comment]
I don't think the topology is changing. I have optimised a couple of these structures manually using GFN2 and GFNFF and there are only small changes. All it says is:

  -T 6 (CPUs/Threads selected)
  -xnam :
     xtb executable was set to: "/home/bruce/exe/xtb-6.4.0/bin/xtb"
  --alpb water : implicit solvation
  --chrg 2

 -------------------------
 xTB Geometry Optimization
 -------------------------

  Initial geometry optimization failed!
  Please check your input.

**Comment by pprcht** [comment]
Alright, fair enough, that isn't the topology related printout. At the moment I can't really tell what is happening. There should be a file `xtb.out` which contains the xtb printout from this attempted optimization, have you compared that with the xTB calculation you did outside of CREST?
If you wish you could privately mail me the in- and output and I'll take a deeper look at it.

**Comment by bfmilne** [comment]
The manual optimisation ends normally with:

optimized geometry written to: xtbopt.xyz


           -------------------------------------------------
          | TOTAL ENERGY             -437.403784110657 Eh   |
          | GRADIENT NORM               0.000286716845 Eh/α |
          | HOMO-LUMO GAP               3.417953157941 eV   |
           -------------------------------------------------

------------------------------------------------------------------------
 * finished run on 2021/02/16 at 11:00:04.298
------------------------------------------------------------------------
 total:
 * wall-time:     0 d,  0 h,  0 min, 14.442 sec
 *  cpu-time:     0 d,  0 h,  0 min, 14.408 sec
 * ratio c/w:     0.998 speedup
 SCF:
 * wall-time:     0 d,  0 h,  0 min,  6.317 sec
 *  cpu-time:     0 d,  0 h,  0 min,  6.301 sec
 * ratio c/w:     0.997 speedup
 ANC optimizer:
 * wall-time:     0 d,  0 h,  0 min,  7.254 sec
 *  cpu-time:     0 d,  0 h,  0 min,  7.246 sec
 * ratio c/w:     0.999 speedup

normal termination of xtb



The xtb.out file ends just after the setup stage:

      -----------------------------------------------------------
     |                   =====================                   |
     |                           x T B                           |
     |                   =====================                   |
     |                         S. Grimme                         |
     |          Mulliken Center for Theoretical Chemistry        |
     |                    University of Bonn                     |
      -----------------------------------------------------------

   * xtb version 6.4.0 (d4b70c2) compiled by 'ehlert@majestix' on 2021-02-01

   xtb is free software: you can redistribute it and/or modify it under
   the terms of the GNU Lesser General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   xtb is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Lesser General Public License for more details.

   Cite this work as:
   * C. Bannwarth, E. Caldeweyher, S. Ehlert, A. Hansen, P. Pracht,
     J. Seibert, S. Spicher, S. Grimme, WIREs Comput. Mol. Sci., 2020,
     e01493. DOI: 10.1002/wcms.1493

   for GFN2-xTB:
   * C. Bannwarth, S. Ehlert and S. Grimme., J. Chem. Theory Comput., 2019,
     15, 1652-1671. DOI: 10.1021/acs.jctc.8b01176
   for GFN1-xTB:
   * S. Grimme, C. Bannwarth, P. Shushkov, J. Chem. Theory Comput., 2017,
     13, 1989-2009. DOI: 10.1021/acs.jctc.7b00118
   for GFN0-xTB:
   * P. Pracht, E. Caldeweyher, S. Ehlert, S. Grimme, ChemRxiv, 2019, preprint.
     DOI: 10.26434/chemrxiv.8326202.v1
   for GFN-FF:
   * S. Spicher and S. Grimme, Angew. Chem. Int. Ed., 2020, 59, 15665-15673.
     DOI: 10.1002/anie.202004239

   for DFT-D4:
   * E. Caldeweyher, C. Bannwarth and S. Grimme, J. Chem. Phys., 2017,
     147, 034112. DOI: 10.1063/1.4993215
   * E. Caldeweyher, S. Ehlert, A. Hansen, H. Neugebauer, S. Spicher,
     C. Bannwarth and S. Grimme, J. Chem. Phys., 2019, 150, 154122.
     DOI: 10.1063/1.5090222
   * E. Caldeweyher, J.-M. Mewes, S. Ehlert and S. Grimme, Phys. Chem. Chem. Phys.
     2020, 22, 8499-8512. DOI: 10.1039/D0CP00502A

   for sTDA-xTB:
   * S. Grimme and C. Bannwarth, J. Chem. Phys., 2016, 145, 054103.
     DOI: 10.1063/1.4959605

   in the mass-spec context:
   * V. Asgeirsson, C. Bauer and S. Grimme, Chem. Sci., 2017, 8, 4879.
     DOI: 10.1039/c7sc00601b
   * J. Koopman and S. Grimme, ACS Omega 2019, 4, 12, 15120-15133.
     DOI: 10.1021/acsomega.9b02011

   for metadynamics refer to:
   * S. Grimme, J. Chem. Theory Comput., 2019, 155, 2847-2862
     DOI: 10.1021/acs.jctc.9b00143

   with help from (in alphabetical order)
   P. Atkinson, C. Bannwarth, F. Bohle, G. Brandenburg, E. Caldeweyher
   M. Checinski, S. Dohm, S. Ehlert, S. Ehrlich, I. Gerasimov, J. Koopman
   C. Lavinge, S. Lehtola, F. März, M. Müller, F. Musil, H. Neugebauer
   J. Pisarek, P. Pracht, J. Seibert, P. Shushkov, S. Spicher, M. Stahn
   T. Strunk, J. Stückrath, T. Rose, and J. Unsleber

 * started run on 2021/02/16 at 10:51:08.439

           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : /home/bruce/exe/xtb-6.4.0/bin/xtb tmpcoord --gfn2 --opt --alpb water
          hostname                   : raio01
          coordinate file            : tmpcoord
          omp threads                :                    14
          number of atoms            :                   286
          number of electrons        :                   776
          charge                     :                     2
          spin                       :                   0.0
          first test random number   :      0.78388834354957

   ID    Z sym.   atoms
    1    7 n      1, 18, 32, 52, 65, 84, 97, 100, 103, 108, 116, 129, 143,
                  157, 167, 178, 198, 208, 216, 229, 243, 257, 272
    2    6 c      2, 3, 5-7, 9, 19, 20, 23, 26, 29, 33, 34, 36-42, 53, 54,
                  56, 57, 66, 67, 71, 74, 76, 80, 85, 86, 88, 91, 94, 99,
                  109, 110, 112-115, 130, 131, 135, 138-140, 144, 145, 148,
                  151, 154, 158, 159, 163, 168, 169, 172, 179, 180, 182-188,
                  199, 200, 203, 209, 210, 212-215, 230, 231, 234, 237, 240,
                  244, 245, 248, 251, 254, 258, 259, 261, 264, 267, 273
    3    8 o      4, 21, 35, 55, 68, 87, 111, 132, 146, 160, 170, 175, 181,
                  201, 211, 232, 246, 260, 268, 269, 277
    4    1 h      8, 10-17, 22, 24, 25, 27, 28, 30, 31, 43-49, 51, 59-64, 69,
                  70, 72, 73, 75, 77-79, 81-83, 89, 90, 92, 93, 95, 96, 98,
                  101, 102, 104-107, 117-128, 133, 134, 136, 137, 141, 142,
                  147, 149, 150, 152, 153, 155, 156, 161, 162, 164-166, 171,
                  173, 174, 176, 177, 189-197, 202, 204, 206, 207, 217-228,
                  233, 235, 236, 238, 239, 241, 242, 247, 249, 250, 252, 253,
                  255, 256, 262, 263, 265, 266, 270, 271, 274-276, 278-286
    5   17 cl     50
    6   16 s      58, 205

           -------------------------------------------------
          |                 G F N 2 - x T B                 |
           -------------------------------------------------

        Reference                      10.1021/acs.jctc.8b01176
      * Hamiltonian:
        H0-scaling (s, p, d)           1.850000    2.230000    2.230000
        zeta-weighting                 0.500000
      * Dispersion:
        s8                             2.700000
        a1                             0.520000
        a2                             5.000000
        s9                             5.000000
      * Repulsion:
        kExp                           1.500000    1.000000
        rExp                           1.000000
      * Coulomb:
        alpha                          2.000000
        third order                    shell-resolved
        anisotropic                    true
        a3                             3.000000
        a5                             4.000000
        cn-shift                       1.200000
        cn-exp                         4.000000
        max-rad                        5.000000

      * Solvation model:               ALPB
        Solvent                        water
        Parameter file                 internal GFN2-xTB/ALPB
        Dielectric constant                8.0200E+01
        Reference state                gsolv [1 M gas/solution]
        Free energy shift                  1.0808E-03 Eh       6.7819E-01 kcal/mol
        Temperature                        2.9815E+02 K
        Density                            1.0000E+00 kg/L
        Solvent mass                       1.8000E+01 g/mol
        Interaction kernel             P16
        Born radius scaling (c1)           1.4744E+00
        Born radii integrator          GBOBC
        Born offset                        0.0000E+00 a0       0.0000E+00 AA
        H-bond correction              true
        Ion screening                  false
        Surface tension                    1.0000E-05 Eh       1.5569E+01 dyn/cm
        Grid points                               974 per atom

          ...................................................
          :                      SETUP                      :
          :.................................................:
          :  # basis functions                 724          :
          :  # atomic orbitals                 721          :
          :  # shells                          429          :
          :  # electrons                       776          :
          :  max. iterations                   250          :
          :  Hamiltonian                  GFN2-xTB          :
          :  restarted?                      false          :
          :  GBSA solvation                   true          :
          :  PC potential                    false          :
          :  electronic temp.          300.0000000     K    :
          :  accuracy                    1.0000000          :
          :  -> integral cutoff          0.2500000E+02      :
          :  -> integral neglect         0.1000000E-07      :
          :  -> SCF convergence          0.1000000E-05 Eh   :
          :  -> wf. convergence          0.1000000E-03 e    :
          :  Broyden damping             0.4000000          :
          ...................................................

**Comment by pprcht** [comment]
Seems that this was a parallelization issue. 
Recompiling xtb 6.4.0 with current intel compilers and MKL was able to solve this.
