### ISSUE TITLE
Typo in src/CMakeLists.txt

### ISSUE THREAD

**Issue by kjelljorner** [grimme-lab/crest#47]
"solvtool.f" should be "solvtool.f90"

https://github.com/grimme-lab/crest/blob/594ef26f266ec0366e4340a349351a7c7c2de0c0/src/CMakeLists.txt#L87

**Comment by awvwgk** [comment]
Thanks for catching this one, mind submitting a patch?

**Comment by kjelljorner** [comment]
My first pull request #48 on external repo on GitHub, hope everything looks OK 😄
