### ISSUE TITLE
Allow entropy calculation for linear molecule

### ISSUE THREAD

**Issue by xiki-tempula** [grimme-lab/crest#50]
The current crest cannot handle oxidates such as BrO or IO. It might be nice for the --entropy to support it.

**Comment by pprcht** [comment]
Do you really mean diatomics BrO and IO? S_conf is zero for those.

**Comment by xiki-tempula** [comment]
@pprcht yes, I know that these are zero but for the purpose of automation. It might be good to give the same output but put zero there.

**Comment by pprcht** [comment]
#51 should fix it
