### ISSUE TITLE
Crest 2.11 does not build due to missing file

### ISSUE THREAD

**Issue by susilehtola** [grimme-lab/crest#52]
Trying to build crest 2.11 for Fedora using meson I get the error
```
meson.build:44:0: ERROR: File combi-scripts/crest_combi does not exist.
```

This file does not appear to exist even in the git source tree

**Comment by awvwgk** [comment]
Has been fixed with https://github.com/grimme-lab/crest/commit/d55d6715893ad950cda29a2c7272b15e6ce76bc3#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a already.

**Comment by awvwgk** [comment]
Duplicate of https://github.com/grimme-lab/crest/issues/36

**Comment by awvwgk** [comment]
Technically #36 is about CMake and this one is about meson, but they both fail for the same reason.
