### ISSUE TITLE
Segmentation fault encountered while testing the installation

### ISSUE THREAD

**Issue by catalystforyou** [grimme-lab/crest#59]
Thank you for sharing the cool program. From the documentation, I found that crest has a lot of useful functions, and I was eager to try. My xtb version is 6.4.0, crest version is 2.11, both the newest version, and I set the OMP_STACKSIZE=5G, ulimit is unlimited. But unfortunately, some weird error happened. 
My operate is quite simple:
`$ crest conf.xyz`
The metadynamics processes went well, but once the program began to optimize geometric data, a segmentation fault occurred:
```
......(skipping the MTD output)
*Meta-MTD 6 finished*
 
-----------------------
Multilevel Optimization
-----------------------
 
 -------------------------
 1. crude pre-optimization
 -------------------------
 Optimizing all 686 structures from file "crest_rotamers_0.xyz" ...
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
crest              00000000024FA974  Unknown               Unknown  Unknown
crest              00000000026CAF50  Unknown               Unknown  Unknown
crest              00000000026BD6A5  Unknown               Unknown  Unknown
crest              0000000002552B7A  Unknown               Unknown  Unknown
crest              0000000000533D3A  Unknown               Unknown  Unknown
crest              0000000002634F43  Unknown               Unknown  Unknown
crest              00000000025EC080  Unknown               Unknown  Unknown
crest              00000000025EB305  Unknown               Unknown  Unknown
crest              0000000002635309  Unknown               Unknown  Unknown
crest              00000000026C7B8E  Unknown               Unknown  Unknown
crest              0000000002738599  Unknown               Unknown  Unknown
```

I searched on Google as well as Github for similar errors for hours but found nothing fruitful, thus I'm seeking your help, thank you so much.

**Comment by catalystforyou** [comment]
I made a silly mistake, now it operates normally, I'll close this issue and thank you all the same.

**Comment by meghnashankar** [comment]
I got the same error on XTB 6.3.2 (the version compatible with the computer I'm using). Would you mind sharing what fixed your error in case it helps?
