### ISSUE TITLE
Issue with cmake installation of crest

### ISSUE THREAD

**Issue by ranjit02** [grimme-lab/crest#69]
I am trying to install crest on a multinode cluster by using the source file of the crest but when I try to build it every time I get following error
![2021-08-04](https://user-images.githubusercontent.com/59292502/128208963-a1ee5d6d-3871-4b6b-acbf-ade512cf31d9.png)

I also export the path of Lapack lib but still, this error is persisting please help me with this.

Thanks and regards
Ranjit

**Comment by awvwgk** [comment]
We are linking against the imported target `LAPACK::LAPACK`, which is buggy in several CMake versions or absent in pre 3.18 if I recall correctly:

https://github.com/grimme-lab/crest/blob/ccb9947fe228241f8c59df5c9847649f2a12f2a9/CMakeLists.txt#L41

To fix this we would have to update the CMake project files to account for
- additionally linking `BLAS::BLAS` target for CMake pre 3.20
- creating imported `LAPACK::LAPACK` target for CMake pre 3.18
