### ISSUE TITLE
[Proposed enhancement] Aligning structures in crest_conformers 

### ISSUE THREAD

**Issue by msh-yi** [grimme-lab/crest#7]
Hello CREST team,

I was wondering if it might be possible for CREST to align the output structures in crest_conformers just before the end of the run. In my experience, the output structures are usually randomly oriented (presumably depending on which MTD run they originated from, and how they were optimized). 

I cannot comment on all use cases, but especially for systems like peptides/proteins, having the conformers all aligned in some way (e.g. RMSD, [like how VMD does it](https://ambermd.org/tutorials/basic/tutorial2/section5.htm)) might help users contrast features between conformers more easily. Sometimes two conformers are really similar except for a local region, but it is not obvious if the two conformers are oriented differently, unless the user manually aligns them.

I hope I'm making sense - thank you!

Marcus

**Comment by pprcht** [comment]
Yes, this makes sense.  Currently the structures are only "aligned"  along the rotational axes, which works fine between rotamers, but not necessarily conformers.

We'll put some (heavy-atom) RMSD alignment in there.

**Comment by pprcht** [comment]
Following `crest` version 2.11 this will be done by default. Currently the development [pre-release](https://github.com/grimme-lab/crest/releases/tag/2.11-dev) is available.
