### ISSUE TITLE
Length of MTD for large molecules

### ISSUE THREAD

**Issue by bfmilne** [grimme-lab/crest#74]
I work with large compounds that always give the warning

! WARNING: the estimated MTD time exceeds 500.0 ps.
! Because the estimate is uncertain, the program restricts
! this to 500.0 ps and continues. The user may
! re-run crest with manual setting by '-mdlen <time>' and
! check the results carefully.

I can try different values of mdlen but this ends up taking a lot of time per compound. Is there any way to get Crest to output the estimate even when it is over 500 ps? (even just to get a rough idea of how long to run)

**Comment by pprcht** [comment]
Hello,
There is no command line argument for this, but if you compiled the program from source you could easily add a printout before the warning. To do so, the printout could be added to routine `V2mdlength` in file `confscript2_main.f90`, line [418](https://github.com/grimme-lab/crest/blob/370d6155d0480ef0decaf7945a4398c68452dd2b/src/confscript2_main.f90#L418). The variables that contain the MD length in ps at this point are `total` and `env%tmtd`. Both should contain the same value in your case.

**Comment by bfmilne** [comment]
Thanks. That will be a great help as I have hundreds of these compounds to process.
