### ISSUE TITLE
CREST on macOS

### ISSUE THREAD

**Issue by misterblonde** [grimme-lab/crest#9]
Hi, 
I was wondering whether it will be possible to use CREST/xtb on Mac OS X? 

Thank you

**Comment by pprcht** [comment]
Hi,
I don't see why it would not work. 
We haven't tried it so far, but will check it prior to updating to version 2.11.

**Comment by alanarnold** [comment]
I’ve been successfully using the current releases of xtb and crest on Ubuntu 20.04 VMs under Parallels 15 on a 12-core Mac Pro (High Sierra) and dual core MacBook Air (Catalina). No problems so far.

**Comment by awvwgk** [comment]
Available from conda-forge now for OSX/x86_64 with https://github.com/conda-forge/crest-feedstock/pull/3#event-5430899701
