### ISSUE TITLE
Crash in crude pre-optimization in Multilevel Optimization stage

### ISSUE THREAD

**Issue by eljost** [grimme-lab/crest#96]
Dear developers,

crest keeps crashing in `1. crude pre-optimization` in the `Multilevel Optimization` stage.
```
...
     Vbias exp α /bohr⁻²:    0.50
Starting Meta-MD   3 with the settings:
     MD time /ps        :    74.0
     dt /fs             :     1.5
     dumpstep(trj) /fs  :     100
     dumpstep(Vbias)/ps :     1.0
     Vbias factor k /Eh :  0.0810
     Vbias exp α /bohr⁻²:    0.50
*Meta-MTD 3 finished*
*Meta-MTD 4 finished*
*Meta-MTD 1 finished*
*Meta-MTD 2 finished*
 
-----------------------
Multilevel Optimization
-----------------------
 
 -------------------------
 1. crude pre-optimization
 -------------------------
 running RMSDs...
 done.
 E lowest :************
forrtl: severe (24): end-of-file during read, unit -9608, file /XXX/projekte/01_daza/02_4ethoxy/16_4ethoxy_educt_crest/crest_rotamers_1.xyz
Image              PC                Routine            Line        Source             
crest              00000000014CE6A8  Unknown               Unknown  Unknown
crest              0000000001503BAA  Unknown               Unknown  Unknown
crest              0000000000670D7A  Unknown               Unknown  Unknown
crest              000000000066FDC8  Unknown               Unknown  Unknown
crest              0000000000664265  Unknown               Unknown  Unknown
crest              000000000068DD28  Unknown               Unknown  Unknown
crest              0000000000402242  Unknown               Unknown  Unknown
crest              00000000016F7DD0  Unknown               Unknown  Unknown
crest              000000000040210E  Unknown               Unknown  Unknown
```

The crash happens with crest `2.11.2` as well as with `2.11.1` in conjunction with `xtb 6.4.1`. All binaries were obtained from github. The crash occurs also on different machines; our local HPC cluster running CentOS 7 (`linux login02 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux `) and my personal machine running Manjaro.

All files from the crest run are found in the attached archive [crest_crash.zip](https://github.com/grimme-lab/crest/files/7812735/crest_crash.zip). The STDOUT is found in `slurm-1579489.out`, the employed geometry is found in `4ed_guess.xyz`.

Maybe you can take a look at it.

All the best,
Johannes

**Comment by pprcht** [comment]
Hello,

I took a look at your output files. 
It seems that this crash happens for the crude pre-optimization step, but only in the third MTD iteration? I.e., two full MTD cycles completed successfully, which is quite strange then.
Do you mind asking, is this issue specific to the molecule you attached, or have you also encountered the crash elsewhere?

I have one (blind) guess at what could be an issue here. It could be the encapsulating wall potential of the `-nci` setting, which is sometimes set too small by the program and crashes calculations. Try to enlarge it a bit with the `--wscal x` command (with a factor x of maybe 1.5 - 2).

**Comment by eljost** [comment]
Thanks for taking a look at the issue. I've never encountered this issue before ... `crest` always worked for me until now.

I'll try your suggestion and let you know if this fixes the issue.

**Comment by eljost** [comment]
Requesting a bigger embedding potential with `-wscal 2` indeed fixed the problem.

Thanks for the help!
